### ISSUE TITLE
Easy way to disable the header

### ISSUE THREAD

**Issue by peti** [massysett/cartel#2]
Hi, thank you very much for writing this fine library. I use it to generate the Cabal file for my `cabal2nix` utility, and I'm quite happy with the results. I have a feature request, though: could you please add an easy way to disable the header that `defaultMain` prepends to the generated file? I realize that I can re-implement `defautMain` with the provided low-level functions to get around that feature, but it would be nice if this were simpler, i.e. by passing a parameter to `defaultMain` or something like that. Thank you!

**Comment by massysett** [comment]
I'd rather keep the defaultMain simple; I think even one more parameter would be too many :) but I will think about this one.  Something like this works fine in the meantime though:

https://gist.github.com/massysett/32ec3cc00f8722a415ba

**Comment by peti** [comment]
Well, if you feel that one parameter is too much, then how about introducing `defaultMail'`, which has that parameter, and making `defaultMain` a wrapper for that new function that sets the argument so that the header is written? Then users wouldn't notice the change, and anyone who cared would have an easy way to disable the advertisement.
