### ISSUE TITLE
cabal function doesn't aggregate multiple entries of the same type

### ISSUE THREAD

**Issue by peti** [massysett/cartel#4]
It would be great if `cabal` would aggregate multiple specifications of the same field into one (and possibly even filter out duplicates). For example:

    λ> let lib = (ghcOptions ["-Wall"] : ghcOptions ["-Wall"] : []) :: [LibraryField]
    λ> putStrLn $ renderIndented 0 $ cabal blank lib []
    description:

    Library
      ghc-options:
          -Wall
      ghc-options:
          -Wall

**Comment by massysett** [comment]
I'd rather keep a simple and direct correspondence between the Cartel types and what winds up in the generated Cabal text.  The programmer may always do this sort of aggregation herself.  It's only cosmetic; Cabal will aggregate these data fields.
